name: Build and Artifact

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Upload Fabric JAR
      uses: actions/upload-artifact@v4
      with:
        name: more-spear-enchantments-fabric
        path: fabric/build/libs/*.jar

    - name: Upload NeoForge JAR
      uses: actions/upload-artifact@v4
      with:
        name: more-spear-enchantments-neoforge
        path: neoforge/build/libs/*.jar

    - name: Upload Common JAR
      uses: actions/upload-artifact@v4
      with:
        name: more-spear-enchantments-common
        path: common/build/libs/*.jar

